"""criar tabelas iniciais

Revision ID: a0325e400e7a
Revises: 
Create Date: 2026-08-19 22:44:21.202322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0325e400e7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_table('encomendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=50), nullable=False),
    sa.Column('transportadora', sa.String(length=80), nullable=True),
    sa.Column('status_atual', sa.String(length=120), nullable=True),
    sa.Column('ultima_consulta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encomendas_codigo_rastreio'), 'encomendas', ['codigo_rastreio'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encomenda_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('local', sa.String(length=120), nullable=True),
    sa.Column('data_evento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encomenda_id'], ['encomendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encomenda_id', 'dedup_hash', name='uq_movimentacao_dedup')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('encomenda_id', sa.UUID(), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('conteudo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['encomenda_id'], ['encomendas.id'], ),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimentacao_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_encomendas_codigo_rastreio'), table_name='encomendas')
    op.drop_table('encomendas')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
